name: github-pages

on:
  push:
    paths:
      - 'CHANGELOG.md'

permissions:
  actions: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: pip install mkdocs mkdocs-material mkdocstrings[python]
      - run: python tools/generate_dl_roadmap.py
      - run: mkdocs build

      - uses: actions/upload-pages-artifact@v2
        with:
          path: site/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
